[package]
name = "css_inspector_suite"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
css_inspector = { path = "../css_inspector" }
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true

